# 01. Pandas 기초 - 실습 문제

## 실습 안내
- 각 문제를 읽고 빈 코드 셀에 답을 작성하세요
- 힌트를 참고하되, 먼저 스스로 해결해보세요
- 실행 결과를 확인하며 진행하세요

## 준비: 라이브러리 불러오기

In [1]:
# 필요한 라이브러리를 import 하세요
import pandas as pd
import numpy as np

pd.set_option('display.max_columns', 20)

---
## 문제 1: 설비 데이터 불러오기 (10점)

`../data/01_equipment.csv` 파일을 읽어서 `equipment_df` 변수에 저장하고, 다음을 출력하세요:
1. 데이터의 처음 3개 행
2. 데이터의 형태 (shape)
3. 컬럼 이름 목록

**힌트**: `read_csv()`, `head()`, `shape`, `columns` 사용

In [8]:
# 여기에 코드를 작성하세요
equipment_df = pd.read_csv('../data/01_equipment.csv')
print('-----장비 정보-----')
print(equipment_df.head(3))
print('\n-----데이터의 형태-----')
print(equipment_df.shape)
print('\n-----컬럼 이름 목록-----')
print(equipment_df.columns)

-----장비 정보-----
  equipment_id equipment_name equipment_type location  rated_capacity  \
0      INJ-001        사출기 1호기            사출기   A동 1라인           150.0
1      INJ-002        사출기 2호기            사출기   A동 1라인           150.0
2    PRESS-001        프레스 1호기            프레스   A동 2라인           200.0

  installation_date  status           created_at           updated_at
0        2020-03-15  ACTIVE  2024-01-01 00:00:00  2024-01-01 00:00:00
1        2021-06-20  ACTIVE  2024-01-01 00:00:00  2024-01-01 00:00:00
2        2019-05-10  ACTIVE  2024-01-01 00:00:00  2024-01-01 00:00:00

-----데이터의 형태-----
(5, 9)

-----컬럼 이름 목록-----
Index(['equipment_id', 'equipment_name', 'equipment_type', 'location',
       'rated_capacity', 'installation_date', 'status', 'created_at',
       'updated_at'],
      dtype='object')

---
## 문제 2: 데이터 정보 확인 (10점)

설비 데이터(`equipment_df`)의 다음 정보를 확인하세요:
1. `info()` 메서드로 데이터 타입과 결측치 확인
2. `describe()` 메서드로 숫자형 컬럼의 기술 통계량 확인

**질문**: 결측치가 있는 컬럼이 있나요? 있다면 어떤 컬럼인가요?

In [9]:
# 여기에 코드를 작성하세요
equipment_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 9 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   equipment_id       5 non-null      object
 1   equipment_name     5 non-null      object
 2   equipment_type     5 non-null      object
 3   location           5 non-null      object
 4   rated_capacity     5 non-null      float64
 5   installation_date  5 non-null      object
 6   status             5 non-null      object
 7   created_at         5 non-null      object
 8   updated_at         5 non-null      object
dtypes: float64(1), object(8)
memory usage: 492.0+ bytes

In [10]:
equipment_df.describe()

       rated_capacity
count        5.000000
mean       160.000000
std         41.833001
min        100.000000
25%        150.000000
50%        150.000000
75%        200.000000
max        200.000000

**답변**: (여기에 답변을 작성하세요)

---
## 문제 3: 생산 데이터 불러오기 및 탐색 (15점)

`../data/05_production.csv` 파일을 읽어서 `production_df` 변수에 저장하고:
1. 총 생산 건수를 출력하세요
2. 처음 10개 행을 확인하세요
3. 다음 컬럼들만 선택하여 새로운 DataFrame을 만들고 처음 5개 행을 출력하세요:
   - `equipment_id`
   - `product_code`
   - `actual_quantity`
   - `good_quantity`
   - `defect_quantity`

In [14]:
# 여기에 코드를 작성하세요
production_df = pd.read_csv('../data/05_production.csv')
print(f'총 생산 건 수 : {production_df['target_quantity'].sum()}')
production_df.head(10)

총 생산 건 수 : 215759

,production_id,equipment_id,product_code,production_date,start_time,end_time,target_quantity,actual_quantity,good_quantity,defect_quantity,cycle_time,work_order_no,lot_no,operator_id,shift,created_at,updated_at
0,1,INJ-001,BUMPER-A,2024-01-01,2024-01-01 08:14:00,2024-01-01 09:53:32,97,81,77,4,73.73,WO202401019935,LOT2024010100101,OP003,DAY,2026-01-30 00:42:48,2026-01-30 00:42:48
1,2,INJ-001,BUMPER-A,2024-01-01,2024-01-01 21:02:00,2024-01-01 22:33:43,83,78,72,6,70.56,WO202401012535,LOT2024010100110,OP006,NIGHT,2026-01-30 00:42:48,2026-01-30 00:42:48
2,3,INJ-002,BUMPER-A,2024-01-01,2024-01-01 10:12:00,2024-01-01 13:16:28,149,135,132,3,81.99,WO202401018359,LOT2024010100201,OP001,DAY,2026-01-30 00:42:48,2026-01-30 00:42:48
3,4,INJ-002,DASH-C,2024-01-01,2024-01-01 12:48:00,2024-01-01 15:16:31,100,92,90,2,96.87,WO202401016574,LOT2024010100202,OP003,DAY,2026-01-30 00:42:48,2026-01-30 00:42:48
4,5,INJ-002,DOOR-B,2024-01-01,2024-01-01 20:48:00,2024-01-01 23:12:13,123,129,122,7,67.08,WO202401012674,LOT2024010100210,OP004,NIGHT,2026-01-30 00:42:48,2026-01-30 00:42:48
5,6,INJ-002,BUMPER-A,2024-01-01,2024-01-02 00:22:00,2024-01-02 03:10:05,124,130,123,7,77.58,WO202401015333,LOT2024010100211,OP005,NIGHT,2026-01-30 00:42:48,2026-01-30 00:42:48
6,7,PRESS-001,DASH-C,2024-01-01,2024-01-01 10:07:00,2024-01-01 12:48:06,128,106,102,4,91.20,WO202401015803,LOT2024010100101,OP010,DAY,2026-01-30 00:42:48,2026-01-30 00:42:48
7,8,PRESS-001,DASH-C,2024-01-01,2024-01-01 14:12:00,2024-01-01 15:58:01,88,73,70,3,87.14,WO202401014733,LOT2024010100102,OP003,DAY,2026-01-30 00:42:48,2026-01-30 00:42:48
8,9,PRESS-001,DOOR-B,2024-01-01,2024-01-01 20:55:00,2024-01-01 22:27:01,92,90,84,6,61.35,WO202401017227,LOT2024010100110,OP004,NIGHT,2026-01-30 00:42:48,2026-01-30 00:42:48
9,10,PRESS-001,DOOR-B,2024-01-01,2024-01-02 02:53:00,2024-01-02 05:09:08,126,123,115,8,66.41,WO202401013664,LOT2024010100111,OP005,NIGHT,2026-01-30 00:42:48,2026-01-30 00:42:48

In [15]:
production_df = pd.read_csv('../data/05_production.csv', usecols=[ 'equipment_id', 'product_code', 'actual_quantity', 'good_quantity','defect_quantity'])
production_df.head(5)

  equipment_id product_code  actual_quantity  good_quantity  defect_quantity
0      INJ-001     BUMPER-A               81             77                4
1      INJ-001     BUMPER-A               78             72                6
2      INJ-002     BUMPER-A              135            132                3
3      INJ-002       DASH-C               92             90                2
4      INJ-002       DOOR-B              129            122                7

---
## 문제 4: 특정 행 선택하기 (15점)

`production_df`에서:
1. `iloc`를 사용하여 10번째 행을 선택하고 출력하세요
2. `iloc`를 사용하여 20~29번째 행(총 10개)을 선택하세요
3. `iloc`를 사용하여 0~4번째 행과 1~5번째 컬럼만 선택하세요

In [30]:
# 1. 10번째 행
production_df = pd.read_csv('../data/05_production.csv')
print(production_df.iloc[10])

production_id                       11
equipment_id                 PRESS-002
product_code                    DOOR-B
production_date             2024-01-01
start_time         2024-01-01 10:17:00
end_time           2024-01-01 11:31:06
target_quantity                     89
actual_quantity                     74
good_quantity                       71
defect_quantity                      3
cycle_time                       60.08
work_order_no           WO202401013803
lot_no                LOT2024010100201
operator_id                      OP002
shift                              DAY
created_at         2026-01-30 00:42:48
updated_at         2026-01-30 00:42:48
Name: 10, dtype: object

In [82]:
# 2. 20~29번째 행
print(pd.DataFrame(production_df.iloc[20:30]))

    production_id equipment_id product_code production_date  \
20             21      INJ-001       DASH-C      2024-01-02
21             22      INJ-001       DOOR-B      2024-01-02
22             23      INJ-001     BUMPER-A      2024-01-02
23             24      INJ-001       DASH-C      2024-01-02
24             25      INJ-002       DASH-C      2024-01-02
25             26      INJ-002       DOOR-B      2024-01-02
26             27      INJ-002       DASH-C      2024-01-02
27             28      INJ-002     BUMPER-A      2024-01-02
28             29    PRESS-001     BUMPER-A      2024-01-02
29             30    PRESS-001       DOOR-B      2024-01-02

             start_time             end_time  target_quantity  \
20  2024-01-02 08:18:00  2024-01-02 11:25:54              135
21  2024-01-02 14:56:00  2024-01-02 16:44:06              113
22  2024-01-02 20:55:00  2024-01-02 23:08:37              118
23  2024-01-03 00:23:00  2024-01-03 02:19:34              100
24  2024-01-02 09:01:00  2024-01-02 11:22:19               94
25  2024-01-02 12:15:00  2024-01-02 14:02:47               90
26  2024-01-02 20:48:00  2024-01-02 23:59:59              148
27  2024-01-03 01:35:00  2024-01-03 03:57:26              101
28  2024-01-02 10:19:00  2024-01-02 12:49:23              131
29  2024-01-02 12:15:00  2024-01-02 14:03:55              108

    actual_quantity  good_quantity  defect_quantity  cycle_time  \
20              128            122                6       88.08
21              107            102                5       60.62
22              112            104                8       71.59
23               95             88                7       73.63
24               98             96                2       86.53
25               94             92                2       68.80
26              155            147                8       83.50
27              106            100                6       80.63
28              128            124                4       70.50
29              105            101                4       62.24

     work_order_no            lot_no operator_id  shift           created_at  \
20  WO202401023591  LOT2024010200101       OP003    DAY  2026-01-30 00:42:48
21  WO202401029201  LOT2024010200102       OP001    DAY  2026-01-30 00:42:48
22  WO202401029317  LOT2024010200110       OP006  NIGHT  2026-01-30 00:42:48
23  WO202401029837  LOT2024010200111       OP004  NIGHT  2026-01-30 00:42:48
24  WO202401026947  LOT2024010200201       OP003    DAY  2026-01-30 00:42:48
25  WO202401022403  LOT2024010200202       OP002    DAY  2026-01-30 00:42:48
26  WO202401023060  LOT2024010200210       OP005  NIGHT  2026-01-30 00:42:48
27  WO202401025342  LOT2024010200211       OP006  NIGHT  2026-01-30 00:42:48
28  WO202401027118  LOT2024010200101       OP002    DAY  2026-01-30 00:42:48
29  WO202401022049  LOT2024010200102       OP010    DAY  2026-01-30 00:42:48

             updated_at
20  2026-01-30 00:42:48
21  2026-01-30 00:42:48
22  2026-01-30 00:42:48
23  2026-01-30 00:42:48
24  2026-01-30 00:42:48
25  2026-01-30 00:42:48
26  2026-01-30 00:42:48
27  2026-01-30 00:42:48
28  2026-01-30 00:42:48
29  2026-01-30 00:42:48

In [32]:
# 3. 0~4번째 행, 1~5번째 컬럼
print(production_df.iloc[:5,1:6])

  equipment_id product_code production_date           start_time  \
0      INJ-001     BUMPER-A      2024-01-01  2024-01-01 08:14:00
1      INJ-001     BUMPER-A      2024-01-01  2024-01-01 21:02:00
2      INJ-002     BUMPER-A      2024-01-01  2024-01-01 10:12:00
3      INJ-002       DASH-C      2024-01-01  2024-01-01 12:48:00
4      INJ-002       DOOR-B      2024-01-01  2024-01-01 20:48:00

              end_time
0  2024-01-01 09:53:32
1  2024-01-01 22:33:43
2  2024-01-01 13:16:28
3  2024-01-01 15:16:31
4  2024-01-01 23:12:13

---
## 문제 5: 단일 조건 필터링 (20점)

`production_df`에서:
1. `equipment_id`가 'PRESS-001'인 데이터만 선택하고, 총 건수를 출력하세요
2. `actual_quantity`(실제 생산량)가 100개 이상인 데이터만 선택하고, 처음 10개를 출력하세요
3. `defect_quantity`(불량 수)가 0인 데이터(완벽한 생산)의 개수를 출력하세요

In [37]:
production_df.columns

Index(['production_id', 'equipment_id', 'product_code', 'production_date',
       'start_time', 'end_time', 'target_quantity', 'actual_quantity',
       'good_quantity', 'defect_quantity', 'cycle_time', 'work_order_no',
       'lot_no', 'operator_id', 'shift', 'created_at', 'updated_at'],
      dtype='object')

In [48]:
# 1. PRESS-001 설비 데이터
production_df[production_df['equipment_id'] == 'PRESS-001'].shape[0]

468

In [49]:
# 2. 생산량 100개 이상
production_df[production_df['actual_quantity'] == 100].head(10)

,production_id,equipment_id,product_code,production_date,start_time,end_time,target_quantity,actual_quantity,good_quantity,defect_quantity,cycle_time,work_order_no,lot_no,operator_id,shift,created_at,updated_at
75,76,PRESS-002,DASH-C,2024-01-04,2024-01-05 02:47:00,2024-01-05 05:09:50,105,100,93,7,85.71,WO202401046967,LOT2024010400211,OP006,NIGHT,2026-01-30 00:42:48,2026-01-30 00:42:48
80,81,INJ-001,DASH-C,2024-01-05,2024-01-05 09:18:00,2024-01-05 11:30:45,106,100,96,4,79.65,WO202401058043,LOT2024010500101,OP001,DAY,2026-01-30 00:42:48,2026-01-30 00:42:48
154,155,PRESS-001,DASH-C,2024-01-08,2024-01-08 09:05:00,2024-01-08 11:26:16,120,100,97,3,84.77,WO202401082899,LOT2024010800101,OP001,DAY,2026-01-30 00:42:48,2026-01-30 00:42:48
178,179,PRESS-001,BUMPER-A,2024-01-09,2024-01-09 10:43:00,2024-01-09 12:43:17,103,100,97,3,72.18,WO202401093785,LOT2024010900101,OP010,DAY,2026-01-30 00:42:48,2026-01-30 00:42:48
190,191,INJ-002,DOOR-B,2024-01-10,2024-01-10 08:12:00,2024-01-10 10:02:01,96,100,98,2,66.02,WO202401109837,LOT2024011000201,OP010,DAY,2026-01-30 00:42:48,2026-01-30 00:42:48
393,394,INJ-001,DOOR-B,2024-01-20,2024-01-20 21:07:00,2024-01-20 23:05:10,106,100,93,7,70.91,WO202401209008,LOT2024012000110,OP006,NIGHT,2026-01-30 00:42:48,2026-01-30 00:42:48
394,395,INJ-002,DASH-C,2024-01-20,2024-01-20 08:29:00,2024-01-20 11:07:34,96,100,98,2,95.15,WO202401209409,LOT2024012000201,OP010,DAY,2026-01-30 00:42:48,2026-01-30 00:42:48
590,591,PRESS-001,DOOR-B,2024-01-30,2024-01-30 09:17:00,2024-01-30 11:03:45,103,100,97,3,64.06,WO202401301427,LOT2024013000101,OP003,DAY,2026-01-30 00:42:48,2026-01-30 00:42:48
643,644,ASM-001,DOOR-B,2024-02-01,2024-02-01 21:52:00,2024-02-01 23:57:35,118,100,92,8,75.36,WO202402016094,LOT2024020100110,OP004,NIGHT,2026-01-30 00:42:48,2026-01-30 00:42:48
734,735,INJ-002,BUMPER-A,2024-02-06,2024-02-06 10:22:00,2024-02-06 12:41:49,96,100,98,2,83.90,WO202402063913,LOT2024020600201,OP003,DAY,2026-01-30 00:42:48,2026-01-30 00:42:48

In [54]:
# 3. 불량 0개 (완벽한 생산)
production_df[production_df['defect_quantity'] == 0].shape[0]

0

---
## 문제 6: 다중 조건 필터링 (20점)

`production_df`에서:
1. `equipment_id`가 'INJ-001'이고 `defect_quantity`가 5개 이상인 데이터를 선택하세요
2. `actual_quantity`가 50개 미만이거나 150개 초과인 데이터를 선택하세요
3. `product_code`가 'BUMPER-A'이고 `good_quantity`가 100개 이상인 데이터의 개수를 출력하세요

In [56]:
# 1. INJ-001 설비 AND 불량 5개 이상
production_df[(production_df['equipment_id'] == 'INJ-001') & (production_df['defect_quantity'] >= 5)]

,production_id,equipment_id,product_code,production_date,start_time,end_time,target_quantity,actual_quantity,good_quantity,defect_quantity,cycle_time,work_order_no,lot_no,operator_id,shift,created_at,updated_at
1,2,INJ-001,BUMPER-A,2024-01-01,2024-01-01 21:02:00,2024-01-01 22:33:43,83,78,72,6,70.56,WO202401012535,LOT2024010100110,OP006,NIGHT,2026-01-30 00:42:48,2026-01-30 00:42:48
20,21,INJ-001,DASH-C,2024-01-02,2024-01-02 08:18:00,2024-01-02 11:25:54,135,128,122,6,88.08,WO202401023591,LOT2024010200101,OP003,DAY,2026-01-30 00:42:48,2026-01-30 00:42:48
21,22,INJ-001,DOOR-B,2024-01-02,2024-01-02 14:56:00,2024-01-02 16:44:06,113,107,102,5,60.62,WO202401029201,LOT2024010200102,OP001,DAY,2026-01-30 00:42:48,2026-01-30 00:42:48
22,23,INJ-001,BUMPER-A,2024-01-02,2024-01-02 20:55:00,2024-01-02 23:08:37,118,112,104,8,71.59,WO202401029317,LOT2024010200110,OP006,NIGHT,2026-01-30 00:42:48,2026-01-30 00:42:48
23,24,INJ-001,DASH-C,2024-01-02,2024-01-03 00:23:00,2024-01-03 02:19:34,100,95,88,7,73.63,WO202401029837,LOT2024010200111,OP004,NIGHT,2026-01-30 00:42:48,2026-01-30 00:42:48
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1813,1814,INJ-001,DASH-C,2024-03-29,2024-03-29 20:48:00,2024-03-29 23:42:43,130,123,101,22,85.23,WO202403291097,LOT2024032900110,OP005,NIGHT,2026-01-30 00:42:48,2026-01-30 00:42:48
1834,1835,INJ-001,BUMPER-A,2024-03-30,2024-03-30 10:06:00,2024-03-30 12:39:25,143,135,118,17,68.19,WO202403308805,LOT2024033000101,OP001,DAY,2026-01-30 00:42:48,2026-01-30 00:42:48
1835,1836,INJ-001,DOOR-B,2024-03-30,2024-03-30 22:50:00,2024-03-30 23:59:59,110,104,85,19,63.56,WO202403303850,LOT2024033000110,OP004,NIGHT,2026-01-30 00:42:48,2026-01-30 00:42:48
1854,1855,INJ-001,DASH-C,2024-03-31,2024-03-31 09:30:00,2024-03-31 12:10:04,118,112,97,15,85.75,WO202403314731,LOT2024033100101,OP003,DAY,2026-01-30 00:42:48,2026-01-30 00:42:48
1855,1856,INJ-001,BUMPER-A,2024-03-31,2024-03-31 20:49:00,2024-03-31 22:41:01,105,99,83,16,67.90,WO202403317215,LOT2024033100110,OP004,NIGHT,2026-01-30 00:42:48,2026-01-30 00:42:48

In [63]:
# 2. 생산량 50개 미만 OR 150개 초과
production_df[~production_df['actual_quantity'].between(50, 150)]

,production_id,equipment_id,product_code,production_date,start_time,end_time,target_quantity,actual_quantity,good_quantity,defect_quantity,cycle_time,work_order_no,lot_no,operator_id,shift,created_at,updated_at
26,27,INJ-002,DASH-C,2024-01-02,2024-01-02 20:48:00,2024-01-02 23:59:59,148,155,147,8,83.50,WO202401023060,LOT2024010200210,OP005,NIGHT,2026-01-30 00:42:48,2026-01-30 00:42:48
44,45,INJ-002,DOOR-B,2024-01-03,2024-01-03 08:37:00,2024-01-03 11:15:13,149,156,152,4,60.86,WO202401031998,LOT2024010300201,OP002,DAY,2026-01-30 00:42:48,2026-01-30 00:42:48
106,107,INJ-002,BUMPER-A,2024-01-06,2024-01-06 20:47:00,2024-01-06 23:59:59,149,156,148,8,88.18,WO202401061853,LOT2024010600210,OP005,NIGHT,2026-01-30 00:42:48,2026-01-30 00:42:48
126,127,INJ-002,DASH-C,2024-01-07,2024-01-07 09:35:00,2024-01-07 13:11:21,147,154,150,4,84.30,WO202401076632,LOT2024010700201,OP003,DAY,2026-01-30 00:42:48,2026-01-30 00:42:48
130,131,INJ-002,BUMPER-A,2024-01-07,2024-01-08 01:17:00,2024-01-08 04:19:13,147,154,146,8,71.00,WO202401075636,LOT2024010700211,OP006,NIGHT,2026-01-30 00:42:48,2026-01-30 00:42:48
172,173,INJ-002,DASH-C,2024-01-09,2024-01-09 09:54:00,2024-01-09 13:43:33,148,155,151,4,88.86,WO202401097226,LOT2024010900201,OP001,DAY,2026-01-30 00:42:48,2026-01-30 00:42:48
194,195,INJ-002,BUMPER-A,2024-01-10,2024-01-11 00:16:00,2024-01-11 03:41:40,148,155,147,8,79.62,WO202401103024,LOT2024011000211,OP005,NIGHT,2026-01-30 00:42:48,2026-01-30 00:42:48
214,215,INJ-002,DASH-C,2024-01-11,2024-01-11 22:02:00,2024-01-11 23:59:59,146,153,145,8,87.67,WO202401115941,LOT2024011100210,OP004,NIGHT,2026-01-30 00:42:48,2026-01-30 00:42:48
257,258,INJ-002,BUMPER-A,2024-01-13,2024-01-13 20:39:00,2024-01-13 23:48:16,144,151,143,8,75.21,WO202401137299,LOT2024011300210,OP006,NIGHT,2026-01-30 00:42:48,2026-01-30 00:42:48
312,313,INJ-002,DOOR-B,2024-01-16,2024-01-16 10:08:00,2024-01-16 13:13:46,147,154,150,4,72.38,WO202401167012,LOT2024011600201,OP001,DAY,2026-01-30 00:42:48,2026-01-30 00:42:48
351,352,INJ-002,DOOR-B,2024-01-18,2024-01-18 14:21:00,2024-01-18 17:31:19,144,151,147,4,75.63,WO202401189351,LOT2024011800202,OP003,DAY,2026-01-30 00:42:48,2026-01-30 00:42:48
374,375,INJ-002,BUMPER-A,2024-01-19,2024-01-19 22:14:00,2024-01-19 23:59:59,148,155,147,8,89.52,WO202401191611,LOT2024011900210,OP006,NIGHT,2026-01-30 00:42:48,2026-01-30 00:42:48
434,435,INJ-002,BUMPER-A,2024-01-22,2024-01-22 22:17:00,2024-01-22 23:59:59,148,155,147,8,86.26,WO202401225697,LOT2024012200210,OP006,NIGHT,2026-01-30 00:42:48,2026-01-30 00:42:48
489,490,INJ-002,DASH-C,2024-01-25,2024-01-25 14:06:00,2024-01-25 18:07:57,148,155,151,4,93.66,WO202401254063,LOT2024012500202,OP001,DAY,2026-01-30 00:42:48,2026-01-30 00:42:48
510,511,INJ-002,DASH-C,2024-01-26,2024-01-26 22:17:00,2024-01-26 23:59:59,148,155,147,8,90.60,WO202401263758,LOT2024012600210,OP005,NIGHT,2026-01-30 00:42:48,2026-01-30 00:42:48
544,545,INJ-002,DOOR-B,2024-01-28,2024-01-28 09:05:00,2024-01-28 11:26:35,145,152,148,4,55.89,WO202401284329,LOT2024012800201,OP001,DAY,2026-01-30 00:42:48,2026-01-30 00:42:48
569,570,INJ-002,DASH-C,2024-01-29,2024-01-30 02:06:00,2024-01-30 05:46:11,144,151,143,8,87.49,WO202401293187,LOT2024012900211,OP004,NIGHT,2026-01-30 00:42:48,2026-01-30 00:42:48
588,589,INJ-002,BUMPER-A,2024-01-30,2024-01-31 00:41:00,2024-01-31 04:13:46,147,154,146,8,82.90,WO202401305082,LOT2024013000211,OP005,NIGHT,2026-01-30 00:42:48,2026-01-30 00:42:48
648,649,INJ-002,DASH-C,2024-02-02,2024-02-02 08:49:00,2024-02-02 12:35:06,147,154,150,4,88.10,WO202402021474,LOT2024020200201,OP010,DAY,2026-01-30 00:42:48,2026-01-30 00:42:48
693,694,INJ-002,DOOR-B,2024-02-04,2024-02-05 00:42:00,2024-02-05 03:43:53,146,153,145,8,71.33,WO202402045423,LOT2024020400211,OP006,NIGHT,2026-01-30 00:42:48,2026-01-30 00:42:48
715,716,INJ-002,DOOR-B,2024-02-05,2024-02-06 06:14:00,2024-02-06 09:27:01,150,157,149,8,73.77,WO202402057203,LOT2024020500212,OP004,NIGHT,2026-01-30 00:42:48,2026-01-30 00:42:48
754,755,INJ-002,DOOR-B,2024-02-07,2024-02-07 09:13:00,2024-02-07 11:55:59,147,154,150,4,63.50,WO202402078780,LOT2024020700201,OP003,DAY,2026-01-30 00:42:48,2026-01-30 00:42:48
758,759,INJ-002,DASH-C,2024-02-07,2024-02-08 02:51:00,2024-02-08 06:26:13,145,152,144,8,84.96,WO202402078300,LOT2024020700211,OP005,NIGHT,2026-01-30 00:42:48,2026-01-30 00:42:48
790,791,INJ-002,DOOR-B,2024-02-09,2024-02-09 09:23:00,2024-02-09 12:20:10,144,151,147,4,70.40,WO202402091173,LOT2024020900201,OP001,DAY,2026-01-30 00:42:48,2026-01-30 00:42:48
833,834,INJ-002,DOOR-B,2024-02-11,2024-02-12 04:50:00,2024-02-12 07:33:10,145,152,144,8,64.41,WO202402119451,LOT2024021100212,OP004,NIGHT,2026-01-30 00:42:48,2026-01-30 00:42:48
872,873,INJ-002,DOOR-B,2024-02-13,2024-02-14 02:37:00,2024-02-14 05:13:27,146,153,145,8,61.35,WO202402138377,LOT2024021300211,OP005,NIGHT,2026-01-30 00:42:48,2026-01-30 00:42:48
891,892,INJ-002,DASH-C,2024-02-14,2024-02-14 13:41:00,2024-02-14 17:38:06,148,155,151,4,91.79,WO202402145404,LOT2024021400202,OP003,DAY,2026-01-30 00:42:48,2026-01-30 00:42:48
910,911,INJ-002,BUMPER-A,2024-02-15,2024-02-15 10:09:00,2024-02-15 13:28:27,148,155,138,17,77.21,WO202402153061,LOT2024021500201,OP003,DAY,2026-01-30 00:42:48,2026-01-30 00:42:48
1017,1018,INJ-002,DOOR-B,2024-02-20,2024-02-20 12:06:00,2024-02-20 14:53:52,146,153,136,17,65.83,WO202402206119,LOT2024022000202,OP010,DAY,2026-01-30 00:42:48,2026-01-30 00:42:48
1021,1022,INJ-002,BUMPER-A,2024-02-20,2024-02-21 06:22:00,2024-02-21 09:40:33,150,157,133,24,75.88,WO202402203319,LOT2024022000212,OP004,NIGHT,2026-01-30 00:42:48,2026-01-30 00:42:48
1110,1111,INJ-002,BUMPER-A,2024-02-24,2024-02-24 22:03:00,2024-02-24 23:59:59,148,155,130,25,77.80,WO202402241476,LOT2024022400210,OP004,NIGHT,2026-01-30 00:42:48,2026-01-30 00:42:48
1212,1213,INJ-002,DOOR-B,2024-02-29,2024-02-29 21:36:00,2024-03-01 00:19:48,145,152,132,20,64.66,WO202402295368,LOT2024022900210,OP006,NIGHT,2026-01-30 00:42:48,2026-01-30 00:42:48
1233,1234,INJ-002,BUMPER-A,2024-03-01,2024-03-02 02:53:00,2024-03-02 06:48:13,147,154,130,24,91.65,WO202403012478,LOT2024030100211,OP006,NIGHT,2026-01-30 00:42:48,2026-01-30 00:42:48
1254,1255,INJ-002,BUMPER-A,2024-03-02,2024-03-02 20:00:00,2024-03-02 23:37:52,147,154,131,23,84.89,WO202403028433,LOT2024030200210,OP006,NIGHT,2026-01-30 00:42:48,2026-01-30 00:42:48
1342,1343,INJ-002,DOOR-B,2024-03-06,2024-03-06 10:35:00,2024-03-06 13:34:36,146,153,136,17,70.43,WO202403065320,LOT2024030600201,OP010,DAY,2026-01-30 00:42:48,2026-01-30 00:42:48
1344,1345,INJ-002,DASH-C,2024-03-06,2024-03-06 20:09:00,2024-03-06 23:59:59,144,151,127,24,94.00,WO202403068499,LOT2024030600210,OP005,NIGHT,2026-01-30 00:42:48,2026-01-30 00:42:48
1345,1346,INJ-002,BUMPER-A,2024-03-06,2024-03-07 02:55:00,2024-03-07 05:58:04,147,154,129,25,71.33,WO202403064483,LOT2024030600211,OP006,NIGHT,2026-01-30 00:42:48,2026-01-30 00:42:48
1366,1367,INJ-002,DASH-C,2024-03-07,2024-03-07 20:31:00,2024-03-07 23:59:59,145,152,131,21,89.11,WO202403077308,LOT2024030700210,OP006,NIGHT,2026-01-30 00:42:48,2026-01-30 00:42:48
1426,1427,INJ-002,BUMPER-A,2024-03-10,2024-03-10 18:48:00,2024-03-10 22:33:32,145,152,133,19,89.03,WO202403109501,LOT2024031000203,OP010,DAY,2026-01-30 00:42:48,2026-01-30 00:42:48
1448,1449,INJ-002,BUMPER-A,2024-03-11,2024-03-11 20:43:00,2024-03-11 23:59:59,150,157,132,25,84.94,WO202403119005,LOT2024031100210,OP004,NIGHT,2026-01-30 00:42:48,2026-01-30 00:42:48
1469,1470,INJ-002,BUMPER-A,2024-03-12,2024-03-12 14:03:00,2024-03-12 17:29:28,146,153,135,18,80.97,WO202403122684,LOT2024031200202,OP010,DAY,2026-01-30 00:42:48,2026-01-30 00:42:48
1555,1556,INJ-002,BUMPER-A,2024-03-16,2024-03-17 01:41:00,2024-03-17 05:05:09,145,152,128,24,80.59,WO202403168856,LOT2024031600211,OP004,NIGHT,2026-01-30 00:42:48,2026-01-30 00:42:48
1575,1576,INJ-002,DOOR-B,2024-03-17,2024-03-17 12:11:00,2024-03-17 15:05:43,147,154,137,17,68.07,WO202403176022,LOT2024031700202,OP001,DAY,2026-01-30 00:42:48,2026-01-30 00:42:48
1618,1619,INJ-002,DASH-C,2024-03-19,2024-03-19 08:04:00,2024-03-19 11:50:30,149,156,138,18,87.12,WO202403195939,LOT2024031900201,OP010,DAY,2026-01-30 00:42:48,2026-01-30 00:42:48
1657,1658,INJ-002,BUMPER-A,2024-03-21,2024-03-21 13:26:00,2024-03-21 17:09:18,150,157,138,19,85.34,WO202403219745,LOT2024032100202,OP002,DAY,2026-01-30 00:42:48,2026-01-30 00:42:48
1676,1677,INJ-002,BUMPER-A,2024-03-22,2024-03-22 09:12:00,2024-03-22 12:53:59,150,157,136,21,84.84,WO202403221530,LOT2024032200201,OP001,DAY,2026-01-30 00:42:48,2026-01-30 00:42:48
1755,1756,INJ-002,BUMPER-A,2024-03-26,2024-03-26 12:57:00,2024-03-26 16:38:10,148,155,139,16,85.62,WO202403261640,LOT2024032600202,OP010,DAY,2026-01-30 00:42:48,2026-01-30 00:42:48
1774,1775,INJ-002,DOOR-B,2024-03-27,2024-03-27 09:42:00,2024-03-27 12:27:38,147,154,135,19,64.54,WO202403275351,LOT2024032700201,OP001,DAY,2026-01-30 00:42:48,2026-01-30 00:42:48
1797,1798,INJ-002,DOOR-B,2024-03-28,2024-03-28 12:37:00,2024-03-28 15:20:53,146,153,136,17,64.27,WO202403283014,LOT2024032800202,OP002,DAY,2026-01-30 00:42:48,2026-01-30 00:42:48
1816,1817,INJ-002,BUMPER-A,2024-03-29,2024-03-29 18:13:00,2024-03-29 21:06:22,146,153,132,21,67.99,WO202403299115,LOT2024032900203,OP001,DAY,2026-01-30 00:42:48,2026-01-30 00:42:48
1859,1860,INJ-002,DASH-C,2024-03-31,2024-04-01 00:26:00,2024-04-01 04:19:55,148,155,133,22,90.55,WO202403311244,LOT2024033100211,OP004,NIGHT,2026-01-30 00:42:48,2026-01-30 00:42:48

In [64]:
# 3. BUMPER-A 제품 AND 양품 100개 이상
production_df[(production_df['product_code'] =='BUMPER-A') & (production_df['good_quantity'] >= 100)]

,production_id,equipment_id,product_code,production_date,start_time,end_time,target_quantity,actual_quantity,good_quantity,defect_quantity,cycle_time,work_order_no,lot_no,operator_id,shift,created_at,updated_at
2,3,INJ-002,BUMPER-A,2024-01-01,2024-01-01 10:12:00,2024-01-01 13:16:28,149,135,132,3,81.99,WO202401018359,LOT2024010100201,OP001,DAY,2026-01-30 00:42:48,2026-01-30 00:42:48
5,6,INJ-002,BUMPER-A,2024-01-01,2024-01-02 00:22:00,2024-01-02 03:10:05,124,130,123,7,77.58,WO202401015333,LOT2024010100211,OP005,NIGHT,2026-01-30 00:42:48,2026-01-30 00:42:48
22,23,INJ-001,BUMPER-A,2024-01-02,2024-01-02 20:55:00,2024-01-02 23:08:37,118,112,104,8,71.59,WO202401029317,LOT2024010200110,OP006,NIGHT,2026-01-30 00:42:48,2026-01-30 00:42:48
27,28,INJ-002,BUMPER-A,2024-01-02,2024-01-03 01:35:00,2024-01-03 03:57:26,101,106,100,6,80.63,WO202401025342,LOT2024010200211,OP006,NIGHT,2026-01-30 00:42:48,2026-01-30 00:42:48
28,29,PRESS-001,BUMPER-A,2024-01-02,2024-01-02 10:19:00,2024-01-02 12:49:23,131,128,124,4,70.50,WO202401027118,LOT2024010200101,OP002,DAY,2026-01-30 00:42:48,2026-01-30 00:42:48
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1844,1845,PRESS-001,BUMPER-A,2024-03-30,2024-03-30 21:40:00,2024-03-30 23:59:59,128,125,107,18,74.30,WO202403302280,LOT2024033000110,OP005,NIGHT,2026-01-30 00:42:48,2026-01-30 00:42:48
1847,1848,PRESS-002,BUMPER-A,2024-03-30,2024-03-30 13:04:00,2024-03-30 15:44:09,148,142,123,19,67.67,WO202403309482,LOT2024033000202,OP002,DAY,2026-01-30 00:42:48,2026-01-30 00:42:48
1860,1861,PRESS-001,BUMPER-A,2024-03-31,2024-03-31 08:08:00,2024-03-31 10:49:26,136,133,114,19,72.83,WO202403311716,LOT2024033100101,OP001,DAY,2026-01-30 00:42:48,2026-01-30 00:42:48
1867,1868,PRESS-002,BUMPER-A,2024-03-31,2024-03-31 20:19:00,2024-03-31 23:25:19,150,144,119,25,77.63,WO202403317101,LOT2024033100210,OP006,NIGHT,2026-01-30 00:42:48,2026-01-30 00:42:48
1870,1871,ASM-001,BUMPER-A,2024-03-31,2024-03-31 10:24:00,2024-03-31 13:25:41,143,121,101,20,90.10,WO202403317268,LOT2024033100101,OP003,DAY,2026-01-30 00:42:48,2026-01-30 00:42:48

---
## 문제 7: isin()과 between() 활용 (10점)

`production_df`에서:
1. `equipment_id`가 'INJ-001', 'INJ-002', 'INJ-003' 중 하나인 데이터를 선택하고 건수를 출력하세요
2. `actual_quantity`가 80~120개 사이인 데이터를 선택하고 처음 5개를 출력하세요

In [65]:
# 1. INJ-001, INJ-002, INJ-003 설비
production_df[production_df['equipment_id'].isin(['INJ-001', 'INJ-002', 'INJ-003' ])]

,production_id,equipment_id,product_code,production_date,start_time,end_time,target_quantity,actual_quantity,good_quantity,defect_quantity,cycle_time,work_order_no,lot_no,operator_id,shift,created_at,updated_at
0,1,INJ-001,BUMPER-A,2024-01-01,2024-01-01 08:14:00,2024-01-01 09:53:32,97,81,77,4,73.73,WO202401019935,LOT2024010100101,OP003,DAY,2026-01-30 00:42:48,2026-01-30 00:42:48
1,2,INJ-001,BUMPER-A,2024-01-01,2024-01-01 21:02:00,2024-01-01 22:33:43,83,78,72,6,70.56,WO202401012535,LOT2024010100110,OP006,NIGHT,2026-01-30 00:42:48,2026-01-30 00:42:48
2,3,INJ-002,BUMPER-A,2024-01-01,2024-01-01 10:12:00,2024-01-01 13:16:28,149,135,132,3,81.99,WO202401018359,LOT2024010100201,OP001,DAY,2026-01-30 00:42:48,2026-01-30 00:42:48
3,4,INJ-002,DASH-C,2024-01-01,2024-01-01 12:48:00,2024-01-01 15:16:31,100,92,90,2,96.87,WO202401016574,LOT2024010100202,OP003,DAY,2026-01-30 00:42:48,2026-01-30 00:42:48
4,5,INJ-002,DOOR-B,2024-01-01,2024-01-01 20:48:00,2024-01-01 23:12:13,123,129,122,7,67.08,WO202401012674,LOT2024010100210,OP004,NIGHT,2026-01-30 00:42:48,2026-01-30 00:42:48
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1855,1856,INJ-001,BUMPER-A,2024-03-31,2024-03-31 20:49:00,2024-03-31 22:41:01,105,99,83,16,67.90,WO202403317215,LOT2024033100110,OP004,NIGHT,2026-01-30 00:42:48,2026-01-30 00:42:48
1856,1857,INJ-002,DASH-C,2024-03-31,2024-03-31 08:24:00,2024-03-31 11:58:52,128,134,119,15,96.21,WO202403318040,LOT2024033100201,OP010,DAY,2026-01-30 00:42:48,2026-01-30 00:42:48
1857,1858,INJ-002,DASH-C,2024-03-31,2024-03-31 14:08:00,2024-03-31 16:31:43,94,98,86,12,88.00,WO202403317024,LOT2024033100202,OP010,DAY,2026-01-30 00:42:48,2026-01-30 00:42:48
1858,1859,INJ-002,DOOR-B,2024-03-31,2024-03-31 21:27:00,2024-03-31 23:12:42,87,91,76,15,69.69,WO202403312507,LOT2024033100210,OP004,NIGHT,2026-01-30 00:42:48,2026-01-30 00:42:48
1859,1860,INJ-002,DASH-C,2024-03-31,2024-04-01 00:26:00,2024-04-01 04:19:55,148,155,133,22,90.55,WO202403311244,LOT2024033100211,OP004,NIGHT,2026-01-30 00:42:48,2026-01-30 00:42:48

In [66]:
# 2. 생산량 80~120개
production_df[production_df['actual_quantity'].between(80, 120)]

,production_id,equipment_id,product_code,production_date,start_time,end_time,target_quantity,actual_quantity,good_quantity,defect_quantity,cycle_time,work_order_no,lot_no,operator_id,shift,created_at,updated_at
0,1,INJ-001,BUMPER-A,2024-01-01,2024-01-01 08:14:00,2024-01-01 09:53:32,97,81,77,4,73.73,WO202401019935,LOT2024010100101,OP003,DAY,2026-01-30 00:42:48,2026-01-30 00:42:48
3,4,INJ-002,DASH-C,2024-01-01,2024-01-01 12:48:00,2024-01-01 15:16:31,100,92,90,2,96.87,WO202401016574,LOT2024010100202,OP003,DAY,2026-01-30 00:42:48,2026-01-30 00:42:48
6,7,PRESS-001,DASH-C,2024-01-01,2024-01-01 10:07:00,2024-01-01 12:48:06,128,106,102,4,91.20,WO202401015803,LOT2024010100101,OP010,DAY,2026-01-30 00:42:48,2026-01-30 00:42:48
8,9,PRESS-001,DOOR-B,2024-01-01,2024-01-01 20:55:00,2024-01-01 22:27:01,92,90,84,6,61.35,WO202401017227,LOT2024010100110,OP004,NIGHT,2026-01-30 00:42:48,2026-01-30 00:42:48
11,12,PRESS-002,DASH-C,2024-01-01,2024-01-01 12:29:00,2024-01-01 14:47:43,128,105,100,5,79.27,WO202401014598,LOT2024010100202,OP002,DAY,2026-01-30 00:42:48,2026-01-30 00:42:48
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1858,1859,INJ-002,DOOR-B,2024-03-31,2024-03-31 21:27:00,2024-03-31 23:12:42,87,91,76,15,69.69,WO202403312507,LOT2024033100210,OP004,NIGHT,2026-01-30 00:42:48,2026-01-30 00:42:48
1861,1862,PRESS-001,DOOR-B,2024-03-31,2024-03-31 14:41:00,2024-03-31 16:42:57,111,108,96,12,67.75,WO202403313125,LOT2024033100102,OP003,DAY,2026-01-30 00:42:48,2026-01-30 00:42:48
1862,1863,PRESS-001,DASH-C,2024-03-31,2024-03-31 21:42:00,2024-03-31 23:57:15,95,93,79,14,87.27,WO202403312251,LOT2024033100110,OP005,NIGHT,2026-01-30 00:42:48,2026-01-30 00:42:48
1869,1870,PRESS-002,BUMPER-A,2024-03-31,2024-04-01 05:53:00,2024-04-01 07:26:15,84,80,66,14,69.95,WO202403317294,LOT2024033100212,OP004,NIGHT,2026-01-30 00:42:48,2026-01-30 00:42:48
1871,1872,ASM-001,DOOR-B,2024-03-31,2024-03-31 20:14:00,2024-03-31 22:16:42,106,90,74,16,81.80,WO202403318062,LOT2024033100110,OP005,NIGHT,2026-01-30 00:42:48,2026-01-30 00:42:48

---
## 도전 문제: 품질 검사 데이터 분석 (보너스 20점)

`../data/07_quality_inspection.csv` 파일을 읽어서 다음을 분석하세요:

1. 전체 검사 건수를 출력하세요
2. `result`가 'FAIL'인 불량 데이터만 선택하세요
3. 불량률(불량 건수 / 전체 건수 * 100)을 계산하여 출력하세요
4. `equipment_id`가 'INJ-001'이고 `result`가 'FAIL'인 데이터의 개수를 출력하세요
5. `measurement_value`(측정값)가 300 미만이거나 310 초과인 데이터를 선택하세요 (규격 이탈)

**힌트**: 위에서 배운 모든 내용을 종합적으로 활용하세요!

In [67]:
df = pd.read_csv('../data/07_quality_inspection.csv')
df.columns

Index(['inspection_id', 'production_id', 'equipment_id', 'product_code',
       'inspection_time', 'inspection_type', 'result', 'defect_code',
       'measurement_value', 'measurement_unit', 'inspector_id', 'lot_no',
       'sample_size', 'notes', 'created_at'],
      dtype='object')

In [69]:
# 여기에 코드를 작성하세요
df = pd.read_csv('../data/07_quality_inspection.csv')
print(f'전체 검사 건 수 : {df.shape[0]}')
print('result가 "FAIL"인 불량 데이터')
print(df[df['result'] == 'FAIL'].head())

전체 검사 건 수 : 37417
result가 "FAIL"인 불량 데이터
    inspection_id  production_id equipment_id product_code  \
7               8              1      INJ-001     BUMPER-A
8               9              1      INJ-001     BUMPER-A
9              10              1      INJ-001     BUMPER-A
10             11              1      INJ-001     BUMPER-A
18             19              2      INJ-001     BUMPER-A

        inspection_time inspection_type result defect_code  measurement_value  \
7   2024-01-01 08:26:47           FINAL   FAIL        D002           305.2058
8   2024-01-01 09:30:37           FINAL   FAIL        D002           314.6991
9   2024-01-01 08:44:05           FINAL   FAIL        D003           293.3244
10  2024-01-01 08:35:47           FINAL   FAIL        D006           287.1234
18  2024-01-01 21:53:40           FINAL   FAIL        D001           291.1185

   measurement_unit inspector_id            lot_no  sample_size  notes  \
7                mm        OP007  LOT2024010100101            1    NaN
8                mm        OP008  LOT2024010100101            1    NaN
9                mm        OP007  LOT2024010100101            1    NaN
10               mm        OP007  LOT2024010100101            1    NaN
18               mm        OP008  LOT2024010100110            1    NaN

             created_at
7   2026-01-30 01:24:59
8   2026-01-30 01:24:59
9   2026-01-30 01:24:59
10  2026-01-30 01:24:59
18  2026-01-30 01:24:59

In [76]:
print(f'불량률 : {len(df[df['result'] =='FAIL']) / len(df) * 100:.2f}')

불량률 : 55.79

In [77]:
# equipment_id가 'INJ-001'이고 result가 'FAIL'인 데이터의 개수를 출력하세요
len(df[(df['equipment_id'] == 'INJ-001') & (df['result'] == 'FAIL')])

3017

In [80]:
# measurement_value(측정값)가 300 미만이거나 310 초과인 데이터를 선택하세요 (규격 이탈)
df[~df['measurement_value'].between(300,310)]

,inspection_id,production_id,equipment_id,product_code,inspection_time,inspection_type,result,defect_code,measurement_value,measurement_unit,inspector_id,lot_no,sample_size,notes,created_at
1,2,1,INJ-001,BUMPER-A,2024-01-01 08:17:24,FINAL,PASS,\N,299.7696,mm,OP008,LOT2024010100101,1,NaN,2026-01-30 01:24:59
4,5,1,INJ-001,BUMPER-A,2024-01-01 09:46:23,FINAL,PASS,\N,299.6097,mm,OP007,LOT2024010100101,1,NaN,2026-01-30 01:24:59
5,6,1,INJ-001,BUMPER-A,2024-01-01 09:34:37,FINAL,PASS,\N,299.6098,mm,OP008,LOT2024010100101,1,NaN,2026-01-30 01:24:59
8,9,1,INJ-001,BUMPER-A,2024-01-01 09:30:37,FINAL,FAIL,D002,314.6991,mm,OP008,LOT2024010100101,1,NaN,2026-01-30 01:24:59
9,10,1,INJ-001,BUMPER-A,2024-01-01 08:44:05,FINAL,FAIL,D003,293.3244,mm,OP007,LOT2024010100101,1,NaN,2026-01-30 01:24:59
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
37412,37413,1872,ASM-001,DOOR-B,2024-03-31 21:13:26,FINAL,FAIL,D002,608.2289,mm,OP008,LOT2024033100110,1,NaN,2026-01-30 01:25:02
37413,37414,1872,ASM-001,DOOR-B,2024-03-31 20:50:20,FINAL,FAIL,D001,609.7039,mm,OP007,LOT2024033100110,1,NaN,2026-01-30 01:25:02
37414,37415,1872,ASM-001,DOOR-B,2024-03-31 20:23:22,FINAL,FAIL,D010,590.4729,mm,OP008,LOT2024033100110,1,NaN,2026-01-30 01:25:02
37415,37416,1872,ASM-001,DOOR-B,2024-03-31 20:44:08,FINAL,FAIL,D001,609.0846,mm,OP008,LOT2024033100110,1,NaN,2026-01-30 01:25:02
37416,37417,1872,ASM-001,DOOR-B,2024-03-31 21:20:30,FINAL,FAIL,D002,612.7437,mm,OP007,LOT2024033100110,1,NaN,2026-01-30 01:25:02